In [78]:
import numpy as np 

n_S = 3
n_A = 3
gamma = 0.9

def get_mdp(n_S, n_A, gamma):
    S = np.arange(n_S)
    A = np.arange(n_A)
    P = np.zeros((n_S, n_S, n_A)) # Prob(s'|s,a)
    for a in range(n_A):
        for s in range(n_S):
            p = np.random.rand(n_S)  # Random values for s'
            P[:, s, a] = p / p.sum()  # Normalize to ensure sum over s' is 1
    R = np.round(np.random.uniform(0,1,(n_S)),1) # R(s)
    return (S, A, P, R, gamma)

M = get_mdp(n_S, n_A, gamma)
(S, A, P, R, gamma) = M
print(M)

(array([0, 1, 2]), array([0, 1, 2]), array([[[0.277272  , 0.25856784, 0.06806276],
        [0.3684607 , 0.44929278, 0.23866789],
        [0.2629952 , 0.29941424, 0.16636881]],

       [[0.38306208, 0.43576104, 0.37098515],
        [0.25908501, 0.09709523, 0.02312625],
        [0.67618646, 0.15400447, 0.45143983]],

       [[0.33966592, 0.30567111, 0.56095209],
        [0.37245429, 0.45361199, 0.73820586],
        [0.06081835, 0.54658129, 0.38219136]]]), array([0.3, 0.5, 0.8]), 0.9)


In [79]:
def get_random_policy(n_S, n_A):
    pi = np.zeros((n_S, n_A))  # Prob(a|s)
    for s in range(n_S):
        p = np.random.rand(n_A)  # Random values for actions
        pi[s, :] = p / p.sum()  # Normalize to ensure sum over actions is 1
    return pi

# Example usage
pi_rand = get_random_policy(n_S, n_A)
print(pi_rand)

[[0.17201566 0.319032   0.50895234]
 [0.08365263 0.42062593 0.49572143]
 [0.33136679 0.5548387  0.11379451]]


In [80]:
def get_optimal_policy(M, T):
    S, A, P, R, gamma = M
    n_S = len(S)
    n_A = len(A)
    
    V = np.zeros((T+1, n_S))  # V[t][s]: value at time t for state s
    
    # Backward induction for finite horizon
    for t in range(T-1, -1, -1):
        for s in range(n_S):
            Q_sa = np.zeros(n_A)
            for a in range(n_A):
                Q_sa[a] = sum(P[s_prime, s, a] * (R[s_prime] + gamma * V[t+1][s_prime]) for s_prime in range(n_S))
            V[t][s] = max(Q_sa)
    
    # Extract optimal policy at t=0
    pi_opt = np.zeros((n_S, n_A))
    for s in range(n_S):
        Q_sa = np.zeros(n_A)
        for a in range(n_A):
            Q_sa[a] = sum(P[s_prime, s, a] * (R[s_prime] + gamma * V[1][s_prime]) for s_prime in range(n_S))
        optimal_action = np.argmax(Q_sa)
        pi_opt[s, optimal_action] = 1
    
    return pi_opt, V[0]


# Example usage
T = 10
pi_opt, V_opt = get_optimal_policy(M, T)
print(pi_opt)
print(V_opt)


[[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]]
[4.12252298 4.13077474 4.07099645]


In [104]:
# initial state distribution 

def get_init_dist(n_S):
    p = np.random.rand(n_S)
    D = p / p.sum()
    return D

def get_init_state(S, D):
    s0 = np.random.choice(S, p = D)
    return s0

D = get_init_dist(n_S)
s0 = get_init_state(S, D)


def get_trajectory(T, M, pi, s0):
    S, A, P, R, gamma = M
    traj_s = [s0]
    traj_a = []
    traj_r = [R[s0]]  # Include reward for the initial state
    for t in range(T):
        s = traj_s[t]
        if np.sum(pi[s]) == 1 and (pi[s] == np.eye(len(A))[np.argmax(pi[s])]).all():
            a = np.argmax(pi[s])
        else:
            a = np.random.choice(A, p=pi[s])
        sp = np.random.choice(S, p=P[:, s, a])
        traj_s.append(sp)
        traj_a.append(a)
        if t + 1 < T:
            traj_r.append(R[sp])
    G = sum(gamma**t * traj_r[t] for t in range(len(traj_r)))
    return traj_s, traj_a, traj_r, G


D = get_init_dist(n_S)
s0 = get_init_state(S, D)
T = 10
traj_s, traj_a, traj_r, G = get_trajectory(T, M, pi_opt, s0)
print("Trajectory States:", traj_s)
print("Trajectory Actions:", traj_a)
print("Trajectory Rewards:", traj_r)
print("Discounted Reward G:", G)


Trajectory States: [2, 0, 2, 2, 0, 2, 2, 2, 1, 0, 2]
Trajectory Actions: [1, 2, 1, 1, 2, 1, 1, 1, 2, 2]
Trajectory Rewards: [0.8, 0.3, 0.8, 0.8, 0.3, 0.8, 0.8, 0.8, 0.5, 0.3]
Discounted Reward G: 4.1096720717


In [114]:
def get_unconditional_G(num_trajectories, T, M, pi, D):
    total_G = 0
    for _ in range(num_trajectories):
        s0 = get_init_state(M[0], D)  # Sample s0 from initial distribution D
        _, _, _, G = get_trajectory(T, M, pi, s0)
        total_G += G
    return total_G / num_trajectories

def get_conditional_G(num_trajectories, T, M, pi, s0):
    total_G = 0
    for _ in range(num_trajectories):
        _, _, _, G = get_trajectory(T, M, pi, s0)  # Use given s0
        total_G += G
    return total_G / num_trajectories

D = get_init_dist(n_S)  # Initialize distribution
num_trajectories = 1000
avg_G_unconditional = get_unconditional_G(num_trajectories, T, M, pi_opt, D)
print(f"Unconditional Average G over D: {avg_G_unconditional}")

s0 = 0  # Specific starting state
avg_G_conditional = get_conditional_G(num_trajectories, T, M, pi_opt, s0)
print(f"Conditional Average G for s0={s0}: {avg_G_conditional}")


Unconditional Average G over D: 4.056193366448799
Conditional Average G for s0=0: 3.783977090678108
